"""Change time to timestamp

Revision ID: 5a6c9fd0e649
Revises: 7e923c62d62a
Create Date: 2018-10-23 18:24:22.782750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a6c9fd0e649'
down_revision = '7e923c62d62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=140), nullable=True),
    sa.Column('destination', sa.String(length=140), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_date'), 'request', ['date'], unique=False)
    op.create_index(op.f('ix_request_time'), 'request', ['time'], unique=False)
    op.add_column('post', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('post', sa.Column('destination', sa.String(length=140), nullable=True))
    op.add_column('post', sa.Column('origin', sa.String(length=140), nullable=True))
    op.create_index(op.f('ix_post_date'), 'post', ['date'], unique=False)
    op.drop_column('post', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.drop_index(op.f('ix_post_date'), table_name='post')
    op.drop_column('post', 'origin')
    op.drop_column('post', 'destination')
    op.drop_column('post', 'date')
    op.drop_index(op.f('ix_request_time'), table_name='request')
    op.drop_index(op.f('ix_request_date'), table_name='request')
    op.drop_table('request')
    # ### end Alembic commands ###
